# Generated by Django 3.2.8 on 2021-11-04 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table=None,
        ),
    ]
