# Generated by Django 3.2.8 on 2021-11-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_address_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
        migrations.AlterModelOptions(
            name='shipping',
            options={'verbose_name_plural': 'Shipping'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='currency_sign',
            new_name='currency',
        ),
    ]
