# Generated by Django 3.2.8 on 2021-11-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211107_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='currency',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
