# Generated by Django 3.2.8 on 2021-11-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='shipping_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
