# Generated by Django 3.2.9 on 2021-11-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_shipping_shipping_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cancel',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
        migrations.AddField(
            model_name='cart',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('cancelled', 'Cancelled'), ('accepted', 'Accepted'), ('default', 'Default')], default='default', max_length=10),
        ),
    ]
