# Generated by Django 3.2.9 on 2021-11-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_cart_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('cancel', 'Cancel'), ('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10),
        ),
    ]
