# Generated by Django 3.2.9 on 2021-11-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('cancel', 'Cancel'), ('pending', 'Pending'), ('approve', 'Approve'), ('disable', 'Disable')], default='pending', max_length=10),
        ),
    ]
