# Generated by Django 3.2.9 on 2021-11-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='shipping_cost',
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
