# Generated by Django 3.2.9 on 2021-11-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_cart_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
