# Generated by Django 3.2.9 on 2021-11-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20211113_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howto',
            name='image',
            field=models.ImageField(default='', upload_to='shop/howto'),
            preserve_default=False,
        ),
    ]
