# Generated by Django 3.2.9 on 2021-11-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_howto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='howto',
            name='step',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
