# Generated by Django 3.2.9 on 2021-11-18 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_howto_step'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='howto',
            options={'ordering': ('step',)},
        ),
    ]
