# Generated by Django 3.2.9 on 2021-11-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_howto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='howto',
            name='video_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
