# Generated by Django 3.2.9 on 2021-11-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_howto_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='stripe_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
