# Generated by Django 3.2.9 on 2021-11-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20211119_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='coin_base_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
