# Generated by Django 3.2.9 on 2021-11-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='original_price',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cart',
            name='sales_price',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
