# Generated by Django 3.2.9 on 2021-12-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20211121_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jumbotron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='jumbotron/')),
                ('order', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], unique=True)),
            ],
        ),
    ]
