# Generated by Django 3.2.9 on 2021-12-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20211207_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
