# Generated by Django 3.2.9 on 2021-12-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_page_popularity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
