# Generated by Django 3.2.9 on 2021-12-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_rename_dob_customer_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping',
            field=models.BooleanField(default=False),
        ),
    ]
